#if defined _ps_bundle_included
 #endinput
#endif
#define _ps_bundle_included

#define KEY_COUNTER "counter"
#define KEY_SESSION "session"
#define KEY_PLAYER_IP "player_ip"
#define KEY_PLAYER_STEAM "player_steam"
#define KEY_PLAYER_NAME "player_name"
#define KEY_PLAYER_ADDRESS_ID "player_address_id"
#define KEY_PLAYER_AUTH_ID "player_auth_id"
#define KEY_PLAYER_NAME_ID "player_name_id"
#define KEY_CONNECTED_ON "connected_on"
#define KEY_DISCONNECTED_ON "disconnected_on"
